version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "webpage-upload-form"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-fdh6tg6rzpg0"
s3_prefix = "webpage-upload-form"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = ["UploadformFunction=814180570813.dkr.ecr.us-east-1.amazonaws.com/webpageuploadformf2575b26/uploadformfunctiona0f5f88erepo"]
